spring:

# redis配置
  redis:
    host: 192.168.1.90
    port: 6379
    password: MuMD02Hov6Xk
##   springboot中开启哨兵(sentinel)模式,只需要在配置文件中增加参数即可
##   当判断master宕机后,会从各slave中选出一台充当master
#    sentinel:
##     主服务器的名称
#      master: sentinelName
##     各节点的ip地址,ipAddress:port,...
#      nodes:

# 数据库
  datasource:
    url: jdbc:mariadb://192.168.1.90:3306/springbootProject
    hikari:
      username: root
      password: zou9RYdAGW2MKoBY
      driver-class-name: org.mariadb.jdbc.Driver


