spring:

  redis:
    host: 192.168.1.90
    port: 36379
    password: XqQjF&80gXZANz

  datasource:
    url: jdbc:mariadb://192.168.1.90:3306/service-admin
    hikari:
      username: root
      password: zou9RYdAGW2MKoBY
      driver-class-name: org.mariadb.jdbc.Driver
