spring:
  thymeleaf:
#    关闭缓存,不利于开发.生产环境可以开启
    cache: false

#    设置thymeleaf的5模式
#    mode: LEGACYHTML5  #设置为传统thml模式,语法可以不那么严格.已被废弃,不推荐使用
    mode: HTML
    encoding: UTF-8  #也可以在html页面设置<meta charset="UTF-8"/>

    # thymeleaf读取页面的默认路径,默认设置为 classpath:/templates/
    prefix: classpath:/templates/
    # 匹配页面后缀
    suffix: .html

  resources:
    # 用于描述静态资源的存放位置，下为springboot默认配置(list)，会**按照顺序**依次查找
    static-locations: classpath:/public,classpath:/static,classpath:/resources,classpath:/META-INF/resources

